### ISSUE TITLE
New feature - possibility to sort according to the date

### ISSUE THREAD

**Issue by henzay** [olibos/HomeAssistant-RecycleApp#107]
Is it possible to implement a sort functionality based on the date? 

For example the first upcoming pick-up will be displayed at first. 

![Image](https://github.com/user-attachments/assets/6c11768a-0f4f-4d06-9b4c-767c42a2c3e8)

**Comment by geertmeersman** [comment]
Hi, you can already sort on the attribute "days"

**Comment by geertmeersman** [comment]
```yaml
type: custom:auto-entities
card:
  square: false
  type: grid
  columns: 2
card_param: cards
filter:
  include:
    - attributes:
        days: "$$*"
      integration: recycle_app
      options:
        type: tile
        show_entity_picture: true
  exclude:
    - state: unknown
show_empty: false
sort:
  method: attribute
  numeric: true
  attribute: days
```

<img width="486" alt="Image" src="https://github.com/user-attachments/assets/91a1bf52-ed0a-4a9e-bb09-24cd5d02ba13" />
