### ISSUE TITLE
Number of days until collection + Enhancement Suggestion

### ISSUE THREAD

**Issue by GiJaLo** [olibos/HomeAssistant-RecycleApp#17]
Thank you for creating the integration for RecycleApp.

I was reviewing previous enhancements and noticed that in version 1.4.0, there was an option to include the number of days until garbage collection. However, when I checked the integration page on RecycleApp, I only saw the option to view garbage entities.

Did I miss something?

As a suggestion, I would like to request the addition of a "today" and "tomorrow" sensor. This would provide more context and make it easier for users to know when their garbage will be collected.

Kind greetings

**Comment by olibos** [comment]
Hello @GiJaLo ,

The number of days is stored as an attribute of the sensor, not as a seperate sensor.
Here is a sample:
![image](https://user-images.githubusercontent.com/6031263/212622058-97cd45a7-7381-429e-9068-fc36004e6bf9.png)

Fot the today & tomorrow sensors, I still don't know if I will implement it in the integration or if I show samples with some cards like [auto-entities](https://github.com/thomasloven/lovelace-auto-entities).

Now that we have the days attribute, it's quite simple to make a filtred list of collections.

Let me know what you think

**Comment by olibos** [comment]
Here is an exemple of a Lovelace card to display next 3 days collections :
```yaml
type: custom:auto-entities
card:
  type: entities
  title: Trash
filter:
  include:
    - device: 1 Boulevard Anspach, 1000 - Bruxelles
      attributes:
        days: <3
  exclude: []
sort:
  method: state
```
![image](https://user-images.githubusercontent.com/6031263/212678174-5fefede8-1785-4337-a804-7b8ebde40aeb.png)

What do you think?
