### ISSUE TITLE
Readme example: screenshot without code

### ISSUE THREAD

**Issue by michaelvandorpe** [olibos/HomeAssistant-RecycleApp#53]
A bit strange to see the "device-filter" sample card in the Readme.md to feature a screenshot (including a screenshot of the code itself), but no way to copy the code. 

Here it is (in Dutch rather than the French in the screenshot):

```
type: entity-filter
entities:
  - sensor.pmd
  - sensor.papier_karton
  - sensor.huisvuil_diftar
  - sensor.kerstbomen
  - sensor.snoeihout
  - sensor.gft_diftar
state_filter:
  - operator: <=
  - value: 1
  - attribute: days
card:
  type: entities
```

(By the way, if anyone sees a way to improve this card by ordering it chronologically by next pickup date, I'd be interested.)

Thanks!

**Comment by michaelvandorpe** [comment]
Correction of my previous code, which contained a mistake:

```
type: entity-filter
entities:
  - sensor.pmd
  - sensor.papier_karton
  - sensor.huisvuil_diftar
  - sensor.kerstbomen
  - sensor.snoeihout
  - sensor.gft_diftar
state_filter:
  - operator: <=
    value: 6
    attribute: days
card:
  type: entities
```
(And with this correction, I don't need the sorting anymore - so you can ignore that part of my bug report.)
